### ISSUE TITLE
 Error: EISDIR: illegal operation on a directory, read 

### ISSUE THREAD

**Issue by pvillaverde** [Koenkk/zigbee2mqtt-chart#21]
Hey there!

I'm trying to deploy the helm chart but I got this error and container keeps restarting:
```
Using '/app/data' as data directory                                                                                                
Error: EISDIR: illegal operation on a directory, read                                                                              
    at Object.readSync (node:fs:744:3)                                                                                             
    at tryReadSync (node:fs:444:20)                                                                                                
    at Object.readFileSync (node:fs:490:19)                                                                                        
    at Object.read (/app/lib/util/yaml.ts:7:37)                                                                                    
    at interpretValue (/app/lib/util/settings.ts:343:25)                                                                           
    at read (/app/lib/util/settings.ts:350:23)                                                                                     
    at getInternalSettings (/app/lib/util/settings.ts:440:21)                                                                      
    at Object.reRead (/app/lib/util/settings.ts:723:5)                                                                             
    at start (/app/index.js:91:14)   
```

I'm using latest helm (1.42.0) and also the container image tag is set to 1.42.0 (Already tried with the 1.37 that the helm chart has default, but I think it's outdated).

**Comment by pvillaverde** [comment]
My apologies, I've just found the issue. I misunderstood this line on the values file:
```
# -- the name for the kubernets secret to mount as secret.yaml. This can be referenced in the config
```
After checking the template I saw that the secret needs the "secret.yaml" key to be mount correctly in the pod. Clossing the issue.
